export const GET_KYC_INFO_REQUEST =
  'APP/Profile/BasicInfo/GET_KYC_INFO_REQUEST';
export const GET_KYC_INFO_SUCCESS =
  'APP/Profile/BasicInfo/GET_KYC_INFO_SUCCESS';
export const GET_KYC_INFO_FAILURE =
  'APP/Profile/BasicInfo/GET_KYC_INFO_FAILURE';

export const UPDATE_BASIC_INFO_REQUEST =
  'APP/Profile/BasicInfo/UPDATE_BASIC_INFO_REQUEST';
export const UPDATE_BASIC_INFO_SUCCESS =
  'APP/Profile/BasicInfo/UPDATE_BASIC_INFO_SUCCESS';
export const UPDATE_BASIC_INFO_FAILURE =
  'APP/Profile/BasicInfo/UPDATE_BASIC_INFO_FAILURE';

export const BASIC_INFO_CLEAR_STATE =
  'APP/Profile/BasicInfo/BASIC_INFO_CLEAR_STATE';

export const FETCH_DOCUMENT_TYPE_REQUEST =
  'APP/Profile/BasicInfo/FETCH_DOCUMENT_TYPE_REQUEST';
export const FETCH_DOCUMENT_TYPE_SUCCESS =
  'APP/Profile/BasicInfo/FETCH_DOCUMENT_TYPE_SUCCESS';
export const FETCH_DOCUMENT_TYPE_FAILURE =
  'APP/Profile/BasicInfo/FETCH_DOCUMENT_TYPE_FAILURE';
