export const FORGOT_PASSWORD_REQUEST = "App/LoginContainer/FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "App/LoginContainer/FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "App/LoginContainer/FORGOT_PASSWORD_FAILURE";

export const RESEND_CONFIRMATION_REQUEST = 'App/LoginContainer/RESEND_CONFIRMATION_REQUEST';
export const RESEND_CONFIRMATION_SUCCESS = 'App/LoginContainer/RESEND_CONFIRMATION_SUCCESS';
export const RESEND_CONFIRMATION_FAILURE = 'App/LoginContainer/RESEND_CONFIRMATION_FAILURE';

export const RESET_FORGOT_PASSWORD = "App/LoginContainer/FORGOT_PASSWORD_RESET";
