/*
 *
 * EmailVerification constants
 *
 */

export const DEFAULT_ACTION = 'app/EmailVerification/DEFAULT_ACTION';

export const RESEND_USER_EMAIL_VERIFICATION_REQUEST =
  'RESEND_USER_EMAIL_VERIFICATION_REQUEST';
export const RESEND_USER_EMAIL_VERIFICATION_SUCCESS =
  'RESEND_USER_EMAIL_VERIFICATION_SUCCESS';
export const RESEND_USER_EMAIL_VERIFICATION_FAILURE =
  'RESEND_USER_EMAIL_VERIFICATION_FAILURE';
