export const VERIFY_ADMIN_EMAIL_TOKEN_REQUEST =
  'app/VerifyAdminEmailToken/VERIFY_ADMIN_EMAIL_TOKEN_REQUEST';
export const VERIFY_ADMIN_EMAIL_TOKEN_SUCCESS =
  'app/VerifyAdminEmailToken/VERIFY_ADMIN_EMAIL_TOKEN_SUCCESS';
export const VERIFY_ADMIN_EMAIL_TOKEN_FAILURE =
  'app/VerifyAdminEmailToken/VERIFY_ADMIN_EMAIL_TOKEN_FAILURE';
