export const GET_TRANSACTION_INFO_REQUEST = 'APP/Wallet/GET_TRANSACTION_INFO_REQUEST';
export const GET_TRANSACTION_INFO_SUCCESS = 'APP/Wallet/GET_TRANSACTION_INFO_SUCCESS';
export const GET_TRANSACTION_INFO_FAILURE = 'APP/Wallet/GET_TRANSACTION_INFO_FAILURE';

export const SEND_WALLET_ADDRESS_REQUEST = 'APP/Wallet/SEND_WALLET_ADDRESS_REQUEST';
export const SEND_WALLET_ADDRESS_SUCCESS = 'APP/Wallet/SEND_WALLET_ADDRESS_SUCCESS';
export const SEND_WALLET_ADDRESS_FAILURE = 'APP/Wallet/SEND_WALLET_ADDRESS_FAILURE';

export const GET_NEW_ADDRESS_REQUEST = 'APP/Wallet/GET_NEW_ADDRESS_REQUEST';
export const GET_NEW_ADDRESS_SUCCESS = 'APP/Wallet/GET_NEW_ADDRESS_SUCCESS';
export const GET_NEW_ADDRESS_FAILURE = 'APP/Wallet/GET_NEW_ADDRESS_FAILURE';

export const GET_BALANCE_REQUEST = 'APP/Wallet/GET_BALANCE_REQUEST';
export const GET_BALANCE_SUCCESS = 'APP/Wallet/GET_BALANCE_SUCCESS';
export const GET_BALANCE_FAILURE = 'APP/Wallet/GET_BALANCE_FAILURE';

export const GET_WALLENT_INFO_REQUEST = 'APP/Wallet/GET_WALLENT_INFO_REQUEST';
export const GET_WALLENT_INFO_SUCCESS = 'APP/Wallet/GET_WALLENT_INFO_SUCCESS';
export const GET_WALLENT_INFO_FAILURE = 'APP/Wallet/GET_WALLENT_INFO_FAILURE';

export const CLEAR_MESSAGE = 'app/ReferShare/CLEAR_MESSAGE';
