export const LOAD_BASIC_INFO_REQUEST =
  'APP/UserDashboard/Main/BasicInfo/LOAD_BASIC_INFO_REQUEST';
export const LOAD_BASIC_INFO_SUCCESS =
  'APP/UserDashboard/Main/BasicInfo/LOAD_BASIC_INFO_SUCCESS';
export const LOAD_BASIC_INFO_FAILURE =
  'APP/UserDashboard/Main/BasicInfo/LOAD_BASIC_INFO_FAILURE';

export const GET_BITCOIN_EXCHANGES_REQUEST =
  'APP/UserDashboard/Main/BasicInfo/GET_BITCOIN_EXCHANGES_REQUEST';
export const GET_BITCOIN_EXCHANGES_SUCCESS =
  'APP/UserDashboard/Main/BasicInfo/GET_BITCOIN_EXCHANGES_SUCCESS';
export const GET_BITCOIN_EXCHANGES_FAILURE =
  'APP/UserDashboard/Main/BasicInfo/GET_BITCOIN_EXCHANGES_FAILURE';

export const CLEAR_MESSAGE = 'app/UserDashboard/Main/CLEAR_MESSAGE';

export const STOP_SHOWING_2FA_ALERT_MESSAGE_REQUEST =
  'STOP_SHOWING_2FA_ALERT_MESSAGE_REQUEST';
