export const RESEND_CONFIRMATION_REQUEST =
  'App/UserDashboard/RESEND_CONFIRMATION_REQUEST';
export const RESEND_CONFIRMATION_SUCCESS =
  'App/UserDashboard/RESEND_CONFIRMATION_SUCCESS';
export const RESEND_CONFIRMATION_FAILURE =
  'App/UserDashboard/RESEND_CONFIRMATION_FAILURE';

export const CLEAR_STATE = 'App/UserDashboard/CLEAR_STATE';

export const FETCH_ALL_USER_NOTIFICATION_REQUEST =
  'App/UserDashboard/FETCH_ALL_USER_NOTIFICATION_REQUEST';
export const FETCH_ALL_USER_NOTIFICATION_SUCCESS =
  'App/UserDashboard/FETCH_ALL_USER_NOTIFICATION_SUCCESS';
export const FETCH_ALL_USER_NOTIFICATION_FAILURE =
  'App/UserDashboard/FETCH_ALL_USER_NOTIFICATION_FAILURE';

export const SEEN_USER_NOTIFICATION_REQUEST =
  'App/UserDashboard/SEEN_USER_NOTIFICATION_REQUEST';
export const SEEN_USER_NOTIFICATION_SUCCESS =
  'App/UserDashboard/SEEN_USER_NOTIFICATION_SUCCESS';
export const SEEN_USER_NOTIFICATION_FAILURE =
  'App/UserDashboard/SEEN_USER_NOTIFICATION_FAILURE';

export const DELETE_USER_NOTIFICATION_REQUEST =
  'App/UserDashboard/DELETE_USER_NOTIFICATION_REQUEST';
export const DELETE_USER_NOTIFICATION_SUCCESS =
  'App/UserDashboard/DELETE_USER_NOTIFICATION_SUCCESS';
export const DELETE_USER_NOTIFICATION_FAILURE =
  'App/UserDashboard/DELETE_USER_NOTIFICATION_FAILURE';

export const SEE_MORE_USER_NOTIFICATION_REQUEST =
  'App/UserDashboard/SEE_MORE_USER_NOTIFICATION_REQUEST';

export const DECREASE_USER_NOTIFICATION_COUNT_REQUEST =
  'App/UserDashboard/DECREASE_USER_NOTIFICATION_COUNT_REQUEST';
