export const VERIFY_MULTI_FACTOR_AUTH_REQUEST =
  'APP/AdminProfile/MultiFactorAuth/VERIFY_MULTI_FACTOR_AUTH_REQUEST';
export const VERIFY_MULTI_FACTOR_AUTH_SUCCESS =
  'APP/AdminProfile/MultiFactorAuth/VERIFY_MULTI_FACTOR_AUTH_SUCCESS';
export const VERIFY_MULTI_FACTOR_AUTH_FAILURE =
  'APP/AdminProfile/MultiFactorAuth/VERIFY_MULTI_FACTOR_AUTH_FAILURE';

export const GET_MULTI_FACTOR_AUTH_REQUEST =
  'APP/AdminProfile/MultiFactorAuth/GET_MULTI_FACTOR_AUTH_REQUEST';
export const GET_MULTI_FACTOR_AUTH_SUCCESS =
  'APP/AdminProfile/MultiFactorAuth/GET_MULTI_FACTOR_AUTH_SUCCESS';
export const GET_MULTI_FACTOR_AUTH_FAILURE =
  'APP/AdminProfile/MultiFactorAuth/GET_MULTI_FACTOR_AUTH_FAILURE';

export const DISABLE_MULTI_FACTOR_AUTH_REQUEST =
  'APP/AdminProfile/MultiFactorAuth/DISABLE_MULTI_FACTOR_AUTH_REQUEST';
export const DISABLE_MULTI_FACTOR_AUTH_SUCCESS =
  'APP/AdminProfile/MultiFactorAuth/DISABLE_MULTI_FACTOR_AUTH_SUCCESS';
export const DISABLE_MULTI_FACTOR_AUTH_FAILURE =
  'APP/AdminProfile/MultiFactorAuth/DISABLE_MULTI_FACTOR_AUTH_FAILURE';

export const GET_RECOVERY_CODES_REQUEST =
  'APP/AdminProfile/MultiFactorAuth/GET_RECOVERY_CODES_REQUEST';
export const GET_RECOVERY_CODES_SUCCESS =
  'APP/AdminProfile/MultiFactorAuth/GET_RECOVERY_CODES_SUCCESS';
export const GET_RECOVERY_CODES_FAILURE =
  'APP/AdminProfile/MultiFactorAuth/GET_RECOVERY_CODES_FAILURE';

export const SEND_EMAIL_WITH_MFA_RECOVERY_REQUEST =
  'APP/AdminProfile/MultiFactorAuth/SEND_EMAIL_WITH_MFA_RECOVERY_REQUEST';
export const SEND_EMAIL_WITH_MFA_RECOVERY_SUCCESS =
  'APP/AdminProfile/MultiFactorAuth/SEND_EMAIL_WITH_MFA_RECOVERY_SUCCESS';
export const SEND_EMAIL_WITH_MFA_RECOVERY_FAILURE =
  'APP/AdminProfile/MultiFactorAuth/SEND_EMAIL_WITH_MFA_RECOVERY_FAILURE';

export const GENERATE_RECOVERY_CODE_REQUEST =
  'APP/AdminProfile/MultiFactorAuth/GENERATE_RECOVERY_CODE_REQUEST';
export const GENERATE_RECOVERY_CODE_SUCCESS =
  'APP/AdminProfile/MultiFactorAuth/GENERATE_RECOVERY_CODE_SUCCESS';
export const GENERATE_RECOVERY_CODE_FAILURE =
  'APP/AdminProfile/MultiFactorAuth/GENERATE_RECOVERY_CODE_FAILURE';

export const LOAD_BASIC_INFO_REQUEST =
  'APP/AdminProfile/BasicInfo/LOAD_BASIC_INFO_REQUEST';
export const LOAD_BASIC_INFO_SUCCESS =
  'APP/AdminProfile/BasicInfo/LOAD_BASIC_INFO_SUCCESS';
export const LOAD_BASIC_INFO_FAILURE =
  'APP/AdminProfile/BasicInfo/LOAD_BASIC_INFO_FAILURE';

export const ENABLE_2FA_AUTH_REQUEST =
  'APP/AdminProfile/MultiFactorAuth/ENABLE_2FA_AUTH_REQUEST';
export const ENABLE_2FA_AUTH_SUCCESS =
  'APP/AdminProfile/MultiFactorAuth/ENABLE_2FA_AUTH_SUCCESS';
export const ENABLE_2FA_AUTH_FAILURE =
  'APP/AdminProfile/MultiFactorAuth/ENABLE_2FA_AUTH_FAILURE';
