export const POST_CUSTOMER_QUERIES_REQUEST =
  'app/ContactPage/POST_CUSTOMER_QUERIES_REQUEST';
export const POST_CUSTOMER_QUERIES_SUCCESS =
  'app/ContactPage/POST_CUSTOMER_QUERIES_SUCCESS';
export const POST_CUSTOMER_QUERIES_FAILURE =
  'app/ContactPage/POST_CUSTOMER_QUERIES_FAILURE';
