export const FETCH_ALL_ADMIN_NOTIFICATION_REQUEST =
  'App/AdminDashboard/FETCH_ALL_ADMIN_NOTIFICATION_REQUEST';
export const FETCH_ALL_ADMIN_NOTIFICATION_SUCCESS =
  'App/AdminDashboard/FETCH_ALL_ADMIN_NOTIFICATION_SUCCESS';
export const FETCH_ALL_ADMIN_NOTIFICATION_FAILURE =
  'App/AdminDashboard/FETCH_ALL_ADMIN_NOTIFICATION_FAILURE';

export const SEEN_ADMIN_NOTIFICATION_REQUEST =
  'App/AdminDashboard/SEEN_ADMIN_NOTIFICATION_REQUEST';
export const SEEN_ADMIN_NOTIFICATION_SUCCESS =
  'App/AdminDashboard/SEEN_ADMIN_NOTIFICATION_SUCCESS';
export const SEEN_ADMIN_NOTIFICATION_FAILURE =
  'App/AdminDashboard/SEEN_ADMIN_NOTIFICATION_FAILURE';

export const DELETE_ADMIN_NOTIFICATION_REQUEST =
  'App/AdminDashboard/DELETE_ADMIN_NOTIFICATION_REQUEST';
export const DELETE_ADMIN_NOTIFICATION_SUCCESS =
  'App/AdminDashboard/DELETE_ADMIN_NOTIFICATION_SUCCESS';
export const DELETE_ADMIN_NOTIFICATION_FAILURE =
  'App/AdminDashboard/DELETE_ADMIN_NOTIFICATION_FAILURE';

export const SEE_MORE_ADMIN_NOTIFICATION_REQUEST =
  'App/AdminDashboard/SEE_MORE_ADMIN_NOTIFICATION_REQUEST';

export const DECREASE_NOTIFICATION_COUNT_REQUEST =
  'App/AdminDashboard/DECREASE_NOTIFICATION_COUNT_REQUEST';
