/*
 *
 * WhereToBuy constants
 *
 */

export const DEFAULT_ACTION = 'app/WhereToBuy/DEFAULT_ACTION';

export const EXCHANGE_LIST = {
  USD: [
    {
      id: 1,
      name: 'Coinbase',
      logo: 'https://s2.coinmarketcap.com/static/img/exchanges/64x64/89.png',
      basedIn: 'United States of America',
      regulated:
        'United States - Financial Crimes Enforcement Network (FinCEN)',
      founded: 'May 2014',
      deposits: [
        'International Wire',
        'Local Bank Transfer',
        'Credit/Debit Card',
      ],
      withdrawals: ['International Wire', 'Local Bank Transfer'],
      officialLink: 'https://pro.coinbase.com',
    },
    {
      id: 2,
      name: 'Kraken',
      logo: 'https://s2.coinmarketcap.com/static/img/exchanges/64x64/24.png',
      basedIn: 'United States of America',
      regulated:
        'United States - Financial Crimes Enforcement Network (FinCEN)',
      founded: 'Jun 2011',
      deposits: ['International Wire', 'Local Bank Transfer'],
      withdrawals: ['International Wire', 'Local Bank Transfer'],
      officialLink: 'https://www.kraken.com',
    },
    {
      id: 3,
      name: 'Binance US',
      logo: 'https://s2.coinmarketcap.com/static/img/exchanges/64x64/630.png',
      basedIn: 'United States of America',
      regulated:
        'United States - Financial Crimes Enforcement Network (FinCEN)',
      founded: 'Sep 2019',
      deposits: [
        'International Wire',
        'Local Bank Transfer',
        'Credit/Debit Card',
      ],
      withdrawals: ['International Wire', 'Local Bank Transfer'],
      officialLink: 'https://www.binance.us/en',
    },
    {
      id: 4,
      name: 'EXMO',
      logo: 'https://s2.coinmarketcap.com/static/img/exchanges/64x64/50.png',
      basedIn: 'United Kingdom of Great Britain and Northern Ireland',
      regulated: '',
      founded: 'Apr 2015',
      deposits: [
        'International Wire',
        '3rd Party Payment',
        'Credit/Debit Card',
      ],
      withdrawals: ['3rd Party Payment'],
      officialLink: 'https://exmo.me/',
    },
    {
      id: 5,
      name: 'CEX.IO',
      logo: 'https://s2.coinmarketcap.com/static/img/exchanges/64x64/36.png',
      basedIn: 'United Kingdom of Great Britain and Northern Ireland',
      regulated: '',
      founded: 'Jun 2013',
      deposits: [
        'International Wire',
        'Local Bank Transfer',
        'Credit/Debit Card',
        '3rd Party Payment',
      ],
      withdrawals: [
        'International Wire',
        'Local Bank Transfer',
        'Credit/Debit Card',
        '3rd Party Payment',
      ],
      officialLink: 'https://cex.io',
    },
    {
      id: 6,
      name: 'Gemini',
      logo: 'https://s2.coinmarketcap.com/static/img/exchanges/64x64/151.png',
      basedIn: 'United States of America',
      regulated:
        'United States - Financial Crimes Enforcement Network (FinCEN)',
      founded: 'Oct 2015',
      deposits: ['International Wire', 'Local Bank Transfer'],
      withdrawals: ['International Wire', 'Local Bank Transfer'],
      officialLink: 'https://gemini.com/',
    },
    {
      id: 7,
      name: 'LocalBitcoins',
      logo:
        'https://miro.medium.com/fit/c/262/262/1*f-TpYWxmhYz1yJKq_HojwQ.png',
      basedIn: 'Finland',
      regulated: 'Finland',
      founded: 'Jun 2012',
      deposits: ['3rd Party Payment'],
      withdrawals: ['3rd Party Payment'],
      officialLink: 'https://localbitcoins.com/',
    },
    {
      id: 8,
      name: 'Paxful',
      logo:
        'https://miro.medium.com/fit/c/262/262/1*CMXCU1dzvJVhZh7bvP26SQ.png',
      basedIn: 'United States of America',
      regulated: 'United States of America',
      founded: 'Jul 2015',
      deposits: ['3rd Party Payment'],
      withdrawals: ['3rd Party Payment'],
      officialLink: 'https://paxful.com/',
    },
    // {
    //   id: 9,
    //   name: 'Bitso',
    //   logo:
    //     'https://static.cryptorival.com/imgs/exchanges/bitso/logo-square.png',
    //   basedIn: 'Mexico',
    //   regulated: '',
    //   founded: '2014',
    //   deposits: ['3rd Party Payment'],
    //   withdrawals: ['3rd Party Payment'],
    //   officialLink: 'https://bitso.com/',
    // },
  ],
  EUR: [
    {
      id: 1,
      name: 'Binance',
      logo: 'https://s2.coinmarketcap.com/static/img/exchanges/64x64/630.png',
      basedIn: 'United Kingdom of Great Britain and Northern Ireland',
      regulated: 'United Kingdom - Financial Conduct Authority (FCA)',
      founded: 'Jul 2017',
      deposits: ['Local Bank Transfer', 'Credit/Debit Card'],
      withdrawals: ['Local Bank Transfer'],
      officialLink: 'https://www.binance.com/',
    },
    {
      id: 2,
      name: 'Coinbase',
      logo: 'https://s2.coinmarketcap.com/static/img/exchanges/64x64/89.png',
      basedIn: 'United Kingdom of Great Britain and Northern Ireland',
      regulated: 'United Kingdom - Financial Conduct Authority (FCA)',
      founded: 'May 2014',
      deposits: ['Local Bank Transfer', 'Credit/Debit Card'],
      withdrawals: ['Local Bank Transfer'],
      officialLink: 'https://pro.coinbase.com',
    },
    {
      id: 3,
      name: 'Kraken',
      logo: 'https://s2.coinmarketcap.com/static/img/exchanges/64x64/24.png',
      basedIn: 'United Kingdom of Great Britain and Northern Ireland',
      regulated: 'United Kingdom - Financial Conduct Authority (FCA)',
      founded: 'Jun 2011',
      deposits: ['International Wire', 'Local Bank Transfer'],
      withdrawals: ['International Wire', 'Local Bank Transfer'],
      officialLink: 'https://www.kraken.com',
    },

    {
      id: 4,
      name: 'Luno',
      logo: 'https://s2.coinmarketcap.com/static/img/exchanges/64x64/151.png',
      basedIn: 'United Kingdom of Great Britain and Northern Ireland',
      regulated: '',
      founded: 'Feb 2017',
      deposits: [
        'Local Bank Transfer',
        '3rd Party Payment',
        'Credit/Debit Card',
      ],
      withdrawals: ['Local Bank Transfer'],
      officialLink: 'https://www.luno.com/en/exchange',
    },

    {
      id: 5,
      name: 'EXMO',
      logo: 'https://s2.coinmarketcap.com/static/img/exchanges/64x64/50.png',
      basedIn: 'United Kingdom of Great Britain and Northern Ireland',
      regulated: '',
      founded: 'Apr 2015',
      deposits: [
        'International Wire',
        'Local Bank Transfer',
        'Credit/Debit Card',
      ],
      withdrawals: ['International Wire', 'Local Bank Transfer'],
      officialLink: 'https://exmo.me/',
    },
    {
      id: 6,
      name: 'CEX.IO',
      logo: 'https://s2.coinmarketcap.com/static/img/exchanges/64x64/36.png',
      basedIn: 'Gibraltar',
      regulated: 'Gibraltar - Gibraltar Financial Services Commission (GFSC)',
      founded: 'Jun 2013',
      deposits: [
        'International Wire',
        'Local Bank Transfer',
        'Credit/Debit Card',
        '3rd Party Payment',
      ],
      withdrawals: [
        'International Wire',
        'Local Bank Transfer',
        'Credit/Debit Card',
        '3rd Party Payment',
      ],
      officialLink: 'https://cex.io',
    },
    {
      id: 7,
      name: 'LocalBitcoins',
      logo:
        'https://miro.medium.com/fit/c/262/262/1*f-TpYWxmhYz1yJKq_HojwQ.png',
      basedIn: 'Finland',
      regulated: 'Finland',
      founded: 'Jun 2012',
      deposits: ['3rd Party Payment'],
      withdrawals: ['3rd Party Payment'],
      officialLink: 'https://localbitcoins.com/',
    },
    {
      id: 8,
      name: 'Paxful',
      logo:
        'https://miro.medium.com/fit/c/262/262/1*CMXCU1dzvJVhZh7bvP26SQ.png',
      basedIn: 'United States of America',
      regulated: 'United States of America',
      founded: 'Jul 2015',
      deposits: ['3rd Party Payment'],
      withdrawals: ['3rd Party Payment'],
      officialLink: 'https://paxful.com/',
    },
    // {
    //   id: 9,
    //   name: 'Bitso',
    //   logo:
    //     'https://static.cryptorival.com/imgs/exchanges/bitso/logo-square.png',
    //   basedIn: 'Mexico',
    //   regulated: '',
    //   founded: '2014',
    //   deposits: ['3rd Party Payment'],
    //   withdrawals: ['3rd Party Payment'],
    //   officialLink: 'https://bitso.com/',
    // },
  ],
  GBP: [
    {
      id: 1,
      name: 'Binance',
      logo: 'https://s2.coinmarketcap.com/static/img/exchanges/64x64/630.png',
      basedIn: 'United Kingdom of Great Britain and Northern Ireland',
      regulated: 'United Kingdom - Financial Conduct Authority (FCA)',
      founded: 'Jul 2017',
      deposits: ['3rd Party Payment'],
      withdrawals: ['Local Bank Transfer'],
      officialLink: 'https://www.binance.com/',
    },
    {
      id: 2,
      name: 'Coinbase',
      logo: 'https://s2.coinmarketcap.com/static/img/exchanges/64x64/89.png',
      basedIn: 'United Kingdom of Great Britain and Northern Ireland',
      regulated: 'United Kingdom - Financial Conduct Authority (FCA)',
      founded: 'May 2014',
      deposits: ['Local Bank Transfer', 'Credit/Debit Card'],
      withdrawals: ['Local Bank Transfer'],
      officialLink: 'https://pro.coinbase.com',
    },
    {
      id: 3,
      name: 'Kraken',
      logo: 'https://s2.coinmarketcap.com/static/img/exchanges/64x64/24.png',
      basedIn: 'United Kingdom of Great Britain and Northern Ireland',
      regulated: 'United Kingdom - Financial Conduct Authority (FCA)',
      founded: 'Jun 2011',
      deposits: ['International Wire', 'Local Bank Transfer'],
      withdrawals: ['International Wire', 'Local Bank Transfer'],
      officialLink: 'https://www.kraken.com',
    },

    {
      id: 4,
      name: 'Luno',
      logo: 'https://s2.coinmarketcap.com/static/img/exchanges/64x64/151.png',
      basedIn: 'United Kingdom of Great Britain and Northern Ireland',
      regulated: '',
      founded: 'Feb 2017',
      deposits: ['Local Bank Transfer'],
      withdrawals: ['Local Bank Transfer'],
      officialLink: 'https://www.luno.com/en/exchange',
    },

    {
      id: 5,
      name: 'EXMO',
      logo: 'https://s2.coinmarketcap.com/static/img/exchanges/64x64/50.png',
      basedIn: 'United Kingdom of Great Britain and Northern Ireland',
      regulated: '',
      founded: 'Apr 2015',
      deposits: [
        'International Wire',
        'Local Bank Transfer',
        'Credit/Debit Card',
      ],
      withdrawals: ['Local Bank Transfer'],
      officialLink: 'https://exmo.me/',
    },
    {
      id: 6,
      name: 'CEX.IO',
      logo: 'https://s2.coinmarketcap.com/static/img/exchanges/64x64/36.png',
      basedIn: 'United Kingdom of Great Britain and Northern Ireland',
      regulated: '',
      founded: 'Jun 2013',
      deposits: [
        'International Wire',
        'Local Bank Transfer',
        'Credit/Debit Card',
        '3rd Party Payment',
      ],
      withdrawals: [
        'International Wire',
        'Local Bank Transfer',
        'Credit/Debit Card',
        '3rd Party Payment',
      ],
      officialLink: 'https://cex.io',
    },
    {
      id: 7,
      name: 'LocalBitcoins',
      logo:
        'https://miro.medium.com/fit/c/262/262/1*f-TpYWxmhYz1yJKq_HojwQ.png',
      basedIn: 'Finland',
      regulated: 'Finland',
      founded: 'Jun 2012',
      deposits: ['3rd Party Payment'],
      withdrawals: ['3rd Party Payment'],
      officialLink: 'https://localbitcoins.com/',
    },
    {
      id: 8,
      name: 'Paxful',
      logo:
        'https://miro.medium.com/fit/c/262/262/1*CMXCU1dzvJVhZh7bvP26SQ.png',
      basedIn: 'United States of America',
      regulated: 'United States of America',
      founded: 'Jul 2015',
      deposits: ['3rd Party Payment'],
      withdrawals: ['3rd Party Payment'],
      officialLink: 'https://paxful.com/',
    },
    // {
    //   id: 9,
    //   name: 'Bitso',
    //   logo:
    //     'https://static.cryptorival.com/imgs/exchanges/bitso/logo-square.png',
    //   basedIn: 'Mexico',
    //   regulated: '',
    //   founded: '2014',
    //   deposits: ['3rd Party Payment'],
    //   withdrawals: ['3rd Party Payment'],
    //   officialLink: 'https://bitso.com/',
    // },
  ],

  NGN: [
    {
      id: 1,
      name: 'Binance',
      logo: 'https://s2.coinmarketcap.com/static/img/exchanges/64x64/630.png',
      basedIn: 'Cayman Islands',
      regulated: 'Cayman Islands - Cayman Islands Monetary Authority',
      founded: 'Jul 2017',
      deposits: ['Local Bank Transfer', '3rd Party Payment'],
      withdrawals: ['3rd Party Payment'],
      officialLink: 'https://www.binance.com/',
    },

    {
      id: 2,
      name: 'Luno',
      logo: 'https://s2.coinmarketcap.com/static/img/exchanges/64x64/151.png',
      basedIn: 'Nigeria',
      regulated: 'Nigeria',
      founded: 'Feb 2017',
      deposits: ['Local Bank Transfer', 'Credit/Debit Card'],
      withdrawals: ['Local Bank Transfer'],
      officialLink: 'https://www.luno.com/en/exchange',
    },
    {
      id: 3,
      name: 'LocalBitcoins',
      logo:
        'https://miro.medium.com/fit/c/262/262/1*f-TpYWxmhYz1yJKq_HojwQ.png',
      basedIn: 'Finland',
      regulated: 'Finland',
      founded: 'Jun 2012',
      deposits: ['3rd Party Payment'],
      withdrawals: ['3rd Party Payment'],
      officialLink: 'https://localbitcoins.com/',
    },
    {
      id: 4,
      name: 'Paxful',
      logo:
        'https://miro.medium.com/fit/c/262/262/1*CMXCU1dzvJVhZh7bvP26SQ.png',
      basedIn: 'United States of America',
      regulated: 'United States of America',
      founded: 'Jul 2015',
      deposits: ['3rd Party Payment'],
      withdrawals: ['3rd Party Payment'],
      officialLink: 'https://paxful.com/',
    },
    // {
    //   id: 5,
    //   name: 'Bitso',
    //   logo:
    //     'https://static.cryptorival.com/imgs/exchanges/bitso/logo-square.png',
    //   basedIn: 'Mexico',
    //   regulated: '',
    //   founded: '2014',
    //   deposits: ['3rd Party Payment'],
    //   withdrawals: ['3rd Party Payment'],
    //   officialLink: 'https://bitso.com/',
    // },
  ],

  RUB: [
    {
      id: 1,
      name: 'Binance',
      logo: 'https://s2.coinmarketcap.com/static/img/exchanges/64x64/630.png',
      basedIn: 'Cayman Islands',
      regulated: 'Cayman Islands - Cayman Islands Monetary Authority',
      founded: 'Jul 2017',
      deposits: ['Credit/Debit Card'],
      withdrawals: ['Credit/Debit Card'],
      officialLink: 'https://www.binance.com/',
    },

    {
      id: 2,
      name: 'EXMO',
      logo: 'https://s2.coinmarketcap.com/static/img/exchanges/64x64/50.png',
      basedIn: 'United Kingdom of Great Britain and Northern Ireland',
      regulated: '',
      founded: 'Apr 2015',
      deposits: ['Credit/Debit Card', '3rd Party Payment'],
      withdrawals: ['Credit/Debit Card', '3rd Party Payment'],
      officialLink: 'https://exmo.me/',
    },
    {
      id: 3,
      name: 'CEX.IO',
      logo: 'https://s2.coinmarketcap.com/static/img/exchanges/64x64/36.png',
      basedIn: 'United Kingdom of Great Britain and Northern Ireland',
      regulated: '',
      founded: 'Jun 2013',
      deposits: ['Credit/Debit Card', '3rd Party Payment'],
      withdrawals: ['Credit/Debit Card', '3rd Party Payment'],
      officialLink: 'https://cex.io',
    },
    {
      id: 4,
      name: 'LocalBitcoins',
      logo:
        'https://miro.medium.com/fit/c/262/262/1*f-TpYWxmhYz1yJKq_HojwQ.png',
      basedIn: 'Finland',
      regulated: 'Finland',
      founded: 'Jun 2012',
      deposits: ['3rd Party Payment'],
      withdrawals: ['3rd Party Payment'],
      officialLink: 'https://localbitcoins.com/',
    },
    {
      id: 5,
      name: 'Paxful',
      logo:
        'https://miro.medium.com/fit/c/262/262/1*CMXCU1dzvJVhZh7bvP26SQ.png',
      basedIn: 'United States of America',
      regulated: 'United States of America',
      founded: 'Jul 2015',
      deposits: ['3rd Party Payment'],
      withdrawals: ['3rd Party Payment'],
      officialLink: 'https://paxful.com/',
    },
    // {
    //   id: 6,
    //   name: 'Bitso',
    //   logo:
    //     'https://static.cryptorival.com/imgs/exchanges/bitso/logo-square.png',
    //   basedIn: 'Mexico',
    //   regulated: '',
    //   founded: '2014',
    //   deposits: ['3rd Party Payment'],
    //   withdrawals: ['3rd Party Payment'],
    //   officialLink: 'https://bitso.com/',
    // },
  ],

  AUD: [
    {
      id: 1,
      name: 'CoinSpot',
      logo:
        'https://www.coinspot.com.au/public/img/coinspot-logo-40x40.png?v=204',
      basedIn: 'Australia',
      regulated: 'Australia',
      founded: '2013',
      deposits: ['Credit/Debit Card', 'Local Bank Transfer'],
      withdrawals: ['Credit/Debit Card', 'Local Bank Transfer'],
      officialLink: 'https://www.coinspot.com.au/',
    },
    {
      id: 2,
      name: 'LocalBitcoins',
      logo:
        'https://miro.medium.com/fit/c/262/262/1*f-TpYWxmhYz1yJKq_HojwQ.png',
      basedIn: 'Finland',
      regulated: 'Finland',
      founded: 'Jun 2012',
      deposits: ['3rd Party Payment'],
      withdrawals: ['3rd Party Payment'],
      officialLink: 'https://localbitcoins.com/',
    },
    {
      id: 3,
      name: 'Paxful',
      logo:
        'https://miro.medium.com/fit/c/262/262/1*CMXCU1dzvJVhZh7bvP26SQ.png',
      basedIn: 'United States of America',
      regulated: 'United States of America',
      founded: 'Jul 2015',
      deposits: ['3rd Party Payment'],
      withdrawals: ['3rd Party Payment'],
      officialLink: 'https://paxful.com/',
    },
    // {
    //   id: 4,
    //   name: 'Bitso',
    //   logo:
    //     'https://static.cryptorival.com/imgs/exchanges/bitso/logo-square.png',
    //   basedIn: 'Mexico',
    //   regulated: '',
    //   founded: '2014',
    //   deposits: ['3rd Party Payment'],
    //   withdrawals: ['3rd Party Payment'],
    //   officialLink: 'https://bitso.com/',
    // },
  ],

  INR: [
    {
      id: 1,
      name: 'WazirX',
      logo: 'https://media.wazirx.com/media/wrx/84.png',
      basedIn: 'India',
      regulated: 'India',
      founded: '2017',
      deposits: ['Credit/Debit Card', 'Local Bank Transfer'],
      withdrawals: ['Credit/Debit Card', 'Local Bank Transfer'],
      officialLink: 'https://wazirx.com/',
    },
    {
      id: 2,
      name: 'LocalBitcoins',
      logo:
        'https://miro.medium.com/fit/c/262/262/1*f-TpYWxmhYz1yJKq_HojwQ.png',
      basedIn: 'Finland',
      regulated: 'Finland',
      founded: 'Jun 2012',
      deposits: ['3rd Party Payment'],
      withdrawals: ['3rd Party Payment'],
      officialLink: 'https://localbitcoins.com/',
    },
    {
      id: 3,
      name: 'Paxful',
      logo:
        'https://miro.medium.com/fit/c/262/262/1*CMXCU1dzvJVhZh7bvP26SQ.png',
      basedIn: 'United States of America',
      regulated: 'United States of America',
      founded: 'Jul 2015',
      deposits: ['3rd Party Payment'],
      withdrawals: ['3rd Party Payment'],
      officialLink: 'https://paxful.com/',
    },
    // {
    //   id: 4,
    //   name: 'Bitso',
    //   logo:
    //     'https://static.cryptorival.com/imgs/exchanges/bitso/logo-square.png',
    //   basedIn: 'Mexico',
    //   regulated: '',
    //   founded: '2014',
    //   deposits: ['3rd Party Payment'],
    //   withdrawals: ['3rd Party Payment'],
    //   officialLink: 'https://bitso.com/',
    // },
  ],
  ZAR: [
    {
      id: 1,
      name: 'Luno',
      logo: 'https://s2.coinmarketcap.com/static/img/exchanges/64x64/151.png',
      basedIn: 'South Africa',
      regulated: 'South Africa',
      founded: 'Feb 2017',
      deposits: [
        'Local Bank Transfer',
        '3rd Party Payment',
        'Credit/Debit Card',
      ],
      withdrawals: ['Local Bank Transfer'],
      officialLink: 'https://www.luno.com/en/exchange',
    },
  ],
  MXN: [
    {
      id: 1,
      name: 'Bitso',
      logo:
        'https://static.cryptorival.com/imgs/exchanges/bitso/logo-square.png',
      basedIn: 'Mexico',
      regulated: 'Mexico',
      founded: 'January 2014',
      deposits: ['3rd Party Payment'],
      withdrawals: ['3rd Party Payment'],
      officialLink: 'https://bitso.com/',
    },
  ],
};

export const currenciesOptions = [
  { key: 'USD', text: 'USD', value: 'USD' },
  { key: 'EUR', text: 'EUR', value: 'EUR' },
  { key: 'AUD', text: 'AUD', value: 'AUD' },
  { key: 'GBP', text: 'GBP', value: 'GBP' },
  { key: 'NGN', text: 'NGN', value: 'NGN' },
  { key: 'RUB', text: 'RUB', value: 'RUB' },
  { key: 'MXN', text: 'MXN', value: 'MXN' },
  { key: 'ZAR', text: 'ZAR', value: 'ZAR' },
  { key: 'INR', text: 'INR', value: 'INR' },
];
